[package]
name = "ink-fresh-language-observation"
version = "0.0.0"
edition = "2024"
[workspace]
[dependencies]
ink-runtime = { path = "../../../../crates/ink-runtime" }
serde_json = "1.0.145"
[patch.crates-io]
rquickjs-sys = { git = "https://github.com/DelSkayn/rquickjs.git", rev = "7a23f6f02f5396b41283b25a0d72f34d8982778e" }
[profile.ink-dev]
inherits = "dev"
debug = 1
opt-level = 2
