[workspace]
resolver = "3"
members = [
  "crates/ink-audio",
  "crates/ink-cli",
  "crates/ink-compiler",
  "crates/ink-core",
  "crates/ink-renderer-vulkan",
  "crates/ink-runtime",
  "platform/android/native",
]

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.96"

[workspace.dependencies]
anyhow = "1.0.100"
ab_glyph = { version = "0.2.32", default-features = false, features = ["std"] }
bytemuck = { version = "1.24.0", features = ["derive"] }
clap = { version = "4.5.47", features = ["derive"] }
image = { version = "0.25.8", default-features = false, features = ["jpeg", "png"] }
indicatif = "0.18.3"
jni = "0.22.4"
miniz_oxide = "0.8.9"
ndk = "0.9.0"
owo-colors = { version = "4.2.3", features = ["supports-colors"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.9.8"
unicode-linebreak = "0.1.5"
unicode-segmentation = "1.13.1"
unicode-properties = { version = "0.1.4", default-features = false, features = ["emoji"] }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"

[profile.ink-dev]
inherits = "dev"
debug = 1
opt-level = 2
