[workspace]
[package]
name = "ink-general-observations"
version = "0.0.0"
edition = "2024"
[dependencies]
ink-core = { path = "../../../../crates/ink-core" }
ink-protocol = { path = "../../../../crates/ink-protocol" }
serde_json = "1.0.145"
[patch.crates-io]
ab_glyph = { path = "../../../../vendor/ab_glyph" }
