[package]
name = "ink-renderer-wgpu"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ab_glyph.workspace = true
anyhow.workspace = true
bytemuck.workspace = true
ink-core = { path = "../ink-core" }
wgpu.workspace = true

[build-dependencies]
naga = { version = "30.0.1", features = ["spv-out", "wgsl-in"] }

[lib]
path = "src/lib.rs"
