[package]
name = "ink-android"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[features]
audio = ["dep:ink-audio", "dep:serde_json"]
network = []

[dependencies]
ink-core = { path = "../../../crates/ink-core" }
ink-audio = { path = "../../../crates/ink-audio", optional = true }
serde_json = { workspace = true, optional = true }
ink-renderer-wgpu = { path = "../../../crates/ink-renderer-wgpu" }
pollster.workspace = true
wgpu.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
jni.workspace = true
ndk = { workspace = true, features = ["rwh_06"] }
