[package]
name = "ink-android"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[features]
audio = ["dep:ink-audio"]
background = []
benchmark = ["ink-core/perf", "ink-renderer-vulkan/perf"]
presentation-timing = ["benchmark", "ink-renderer-vulkan/presentation-timing", "dep:libc"]
memory-diagnostics = ["ink-core/perf", "ink-renderer-vulkan/perf"]
image = ["ink-renderer-vulkan/image"]
network = []
camera-photo = ["image"]

[dependencies]
ink-core = { path = "../../../crates/ink-core" }
ink-runtime = { path = "../../../crates/ink-runtime" }
anyhow.workspace = true
ink-audio = { path = "../../../crates/ink-audio", optional = true }
serde_json.workspace = true
ink-renderer-vulkan = { path = "../../../crates/ink-renderer-vulkan" }

[target.'cfg(target_os = "android")'.dependencies]
libc = { version = "0.2", optional = true }
jni.workspace = true
ndk = { workspace = true, features = ["rwh_06"] }
