[package]
name = "ink-android"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[features]
ui-lists = ["ink-core/ui-lists"]
ui-playing = ["ink-core/ui-playing"]
ui-messages = ["ink-core/ui-messages"]
ui-canvas = ["ink-core/ui-canvas"]
text-input = ["ink-core/text-input"]
camera = ["ink-core/camera"]
video = ["ink-core/video"]
maps = ["ink-core/maps"]
audio = ["dep:ink-audio"]
background = []
benchmark = ["ink-core/perf", "ink-renderer-vulkan/perf"]
bridge-timing = ["dep:libc"]
presentation-timing = ["bridge-timing", "benchmark", "ink-renderer-vulkan/presentation-timing"]
memory-diagnostics = ["ink-core/perf", "ink-renderer-vulkan/perf"]
image = ["ink-renderer-vulkan/image"]
network = []
camera-photo = ["image"]

[dependencies]
ink-core = { path = "../../../crates/ink-core", default-features = false }
ink-runtime = { path = "../../../crates/ink-runtime" }
anyhow.workspace = true
ink-audio = { path = "../../../crates/ink-audio", optional = true }
serde_json.workspace = true
serde.workspace = true
ink-renderer-vulkan = { path = "../../../crates/ink-renderer-vulkan" }

[target.'cfg(target_os = "android")'.dependencies]
libc = { version = "0.2", optional = true }
jni.workspace = true
ndk = { workspace = true, features = ["rwh_06"] }
parking_lot = { version = "0.12.5", features = ["arc_lock"] }
