import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const codepoints = await Bun.file(resolve(root, "assets/icons/MaterialSymbolsOutlined.codepoints")).text();
const symbols = new Map(codepoints.trim().split("\n").map(line => {
  const [name, codepoint] = line.split(/\s+/);
  return [name, codepoint];
}));
const reserved = new Set("break case catch class const continue debugger default delete do else enum export extends false finally for function if import in instanceof new null return super switch this throw true try typeof var void while with implements interface let package private protected public static yield await".split(" "));
const exports = new Set<string>();
const lines = [
  "// Generated by scripts/generate-icons.ts from the bundled Material Symbols catalogue.",
  'import type { IconAsset } from "./assets";',
  "",
];
for (const [name, codepoint] of symbols) {
  if (name.endsWith("_filled") && symbols.get(name.slice(0, -7)) === codepoint) continue;
  let identifier = name.replace(/_([a-z0-9])/g, (_, character: string) => character.toUpperCase());
  if (/^\d/.test(identifier)) identifier = `icon${identifier}`;
  if (reserved.has(identifier) || identifier.endsWith("Filled")) identifier += "Icon";
  for (const filled of [false, true]) {
    const key = identifier + (filled ? "Filled" : "");
    if (exports.has(key)) throw new Error(`Duplicate icon export: ${key}`);
    exports.add(key);
    lines.push(`export const ${key} = "${filled ? "filled" : "outlined"}:${name}" as IconAsset;`);
  }
}
await Bun.write(resolve(root, "packages/ink/src/icons.ts"), lines.join("\n") + "\n");
